
- name: "Create /opt dir"
  shell: 'mkdir -p /opt'
  tags: up

- name: "Copy build files"
  copy:
    src: '.'
    dest: '/opt/{{ role_name }}/'
    mode: 0755
  tags: up

- name: "Git ton-q-server checkout"
  git:
    repo: 'https://github.com/tonlabs/ton-q-server.git'
    dest: /opt/{{ role_name }}/build/ton-q-server
  tags: up  
  
- name: "Template docker-compose.yml"
  template:
    src: 'docker-compose.yml'
    dest: '/opt/{{ role_name }}'
    mode: 0755
  tags: up


    
- name: "Run docker-compose"
  shell: 'cd /opt/{{ role_name }} && docker-compose up -d --build'
  tags: up

- name: "Shut down docker-compose"
  shell: 'cd /opt/{{ role_name }} && docker-compose down'
  tags: down
