version: '2.3'
services:
  arangodb:
    build:
      context: ./build
    # image: tonlabs/arango:latest
    container_name: arangodb
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: 1
      VIRTUAL_HOST: arango.baremetal01.fra02.ibm.cloud
      VIRTUAL_PORT: 8529
      LETSENCRYPT_HOST: arango.baremetal01.fra02.ibm.cloud
      LETSENCRYPT_EMAIL: "senegalelastico@gmail.com"
      ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: 343579738368
    networks:
      - proxy_nw
    volumes:
      - db3:/var/lib/arangodb3
      - data:/arango/db
      - ./arango-config:/arango/config
    expose:
      - "8529"
    mem_limit: 32G
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "arangodb"

  arangodbni:
    build:
      context: ./build
    # image: tonlabs/arango:latest
    container_name: arangodbni
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: 1
      VIRTUAL_HOST: arangoni.baremetal01.fra02.ibm.cloud
      VIRTUAL_PORT: 8529
      LETSENCRYPT_HOST: arangoni.baremetal01.fra02.ibm.cloud
      LETSENCRYPT_EMAIL: "senegalelastico@gmail.com"
    networks:
      - proxy_nw
    volumes:
      - db3ni:/var/lib/arangodb3
      - datani:/arango/db
      - ./arangoni-config:/arango/config
    expose:
      - "8529"
    mem_limit: 32G
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "arangodbni"

networks:
  proxy_nw:
    external: true
volumes:
  data:
  db3:
  datani:
  db3ni:
