version: '2'
services:
  web.root:
    image: nginx:1.13.12
    container_name: web.root
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${HOSTpublic}
      - LETSENCRYPT_HOST=${HOSTpublic}
      - LETSENCRYPT_EMAIL="senegalelastico@gmail.com"
    networks:
      - proxy_nw
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    expose:
      - "80"
    logging: 
      driver: gelf 
      options:
        gelf-address: "udp://localhost:12201"
        tag: "web.root"

networks:
  proxy_nw:
    external: true
